const crypto = require("crypto");
function headers(extra){const key=process.env.SUPABASE_SECRET_KEY||"";const h={apikey:key,"Content-Type":"application/json"};if(key.startsWith("eyJ"))h.Authorization="Bearer "+key;return Object.assign(h,extra||{});}
function secret(){return process.env.BUSINESS_SESSION_SECRET||process.env.SUPABASE_SECRET_KEY||"";}
function b64(v){return Buffer.from(v).toString("base64url");}
function sign(payload){const body=b64(JSON.stringify(payload));const sig=crypto.createHmac("sha256",secret()).update(body).digest("base64url");return body+"."+sig;}
function verify(token){try{const parts=String(token||"").split(".");if(parts.length!==2)return null;const expected=crypto.createHmac("sha256",secret()).update(parts[0]).digest("base64url");const a=Buffer.from(parts[1]),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const p=JSON.parse(Buffer.from(parts[0],"base64url").toString("utf8"));if(!p||!p.business_id||!p.agenda_token||!p.exp||Date.now()>p.exp)return null;return p;}catch(e){return null;}}
function cookie(req,name){const raw=String(req.headers.cookie||"");for(const part of raw.split(";")){const i=part.indexOf("=");if(i>0&&part.slice(0,i).trim()===name)return decodeURIComponent(part.slice(i+1).trim());}return "";}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");res.setHeader("X-Robots-Tag","noindex");if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SECRET_KEY)return res.status(503).json({error:"Servizio non disponibile"});
if(req.method==="POST"){const email=String((req.body||{}).email||"").trim().toLowerCase();const password=String((req.body||{}).password||"");if(!email||!password)return res.status(400).json({error:"Inserisci email e password"});const r=await fetch(process.env.SUPABASE_URL+"/rest/v1/rpc/business_login",{method:"POST",headers:headers(),body:JSON.stringify({p_email:email,p_password:password})});const data=await r.json().catch(()=>[]);if(!r.ok)return res.status(502).json({error:"Accesso temporaneamente non disponibile"});if(!Array.isArray(data)||!data.length)return res.status(401).json({error:"Email o password non corretti"});const row=data[0],exp=Date.now()+43200000;const token=sign({business_id:row.business_id,agenda_token:row.agenda_token,business_name:row.business_name,exp});res.setHeader("Set-Cookie","lia_business_session="+encodeURIComponent(token)+"; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200");return res.status(200).json({ok:true,business_name:row.business_name});}
if(req.method==="DELETE"){res.setHeader("Set-Cookie","lia_business_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0");return res.status(200).json({ok:true});}
if(req.method==="GET"){const p=verify(cookie(req,"lia_business_session"));if(!p)return res.status(401).json({authenticated:false});return res.status(200).json({authenticated:true,business_name:p.business_name,agenda_token:p.agenda_token});}
res.setHeader("Allow","GET, POST, DELETE");return res.status(405).json({error:"Metodo non consentito"});};
module.exports.verifyBusinessSession=verify;module.exports.readBusinessCookie=cookie;
